---
- name: install OS related packages
  include_tasks: '{{ install }}'
  with_first_found:
    - 'install/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - 'install/{{ ansible_distribution }}.yml'
    - 'install/{{ ansible_os_family }}-{{ ansible_pkg_mgr }}.yml'
    - 'install/{{ ansible_os_family }}.yml'
    - 'install/{{ ansible_os_family | replace ("/","_") | replace(" ","_") }}.yml'
    - install/defaults.yml
  loop_control:
    loop_var: install
  tags:
    - install
  when:
    - ansible_distribution is defined
    - ansible_os_family is defined
    - ansible_distribution_major_version is defined
