---
- name: Set OS related variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ _packages_to_install | default([]) }}"
  loop_control:
    loop_var: pkg
