---
- name: DEBUG show qemu_img
  ansible.builtin.debug:
    var:
      qemu_img
  tags:
    - debug
    - never

- name: Install qemu img
  ansible.builtin.include_tasks:
    install.yml
  args:
    apply:
      tags:
        - install

- name: Fail if qemu_img is not defined
  ansible.builtin.fail:
    msg: qemu_img is not defined
  when:
    - qemu_img is not defined

- name: Copy to _qemu_images
  ansible.builtin.set_fact:
    _qemu_images:
      "{{ qemu_img }}"
  when:
    - qemu_img | type_debug == "list"

- name: Convert to array
  ansible.builtin.set_fact:
    _qemu_images:
      "[ {{ qemu_img }} ]"
  when:
    - qemu_img | type_debug != "list"

- name: DEBUG show _qemu_images
  ansible.builtin.debug:
    var:
      _qemu_images
  when:
    - _qemu_images | type_debug == "list"
  tags:
    - debug
    - never

- name: DEBUG Loop over the qemu images
  ansible.builtin.debug:
    var:
      _qemu_image
  loop: "{{ _qemu_images }}"
  loop_control:
    loop_var: _qemu_image

- name: Loop over the qemu images
  ansible.builtin.include_tasks:
    qemu_image.yml
  loop: "{{ _qemu_images }}"
  loop_control:
    loop_var: _qemu_image
