---
- name: Create a new disk image
  gather_facts: false
  become: true
  hosts: localhost
  roles:
    - role: stafwag.qemu_img
      vars:
        qemu_img:
          dest: datadisk.qcow2
          size: 20G
          format: qcow2
